package com.fossiles.fossilescorebackend.application.service;

import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

import java.util.List;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;

/** Lee la tabla real del módulo Supervisoras y kioscos (H2 en modo PostgreSQL) sin depender de sus clases. */
class KioskSupervisorAssignmentReaderTest {

    private static JdbcTemplate freshDb() {
        DriverManagerDataSource ds = new DriverManagerDataSource(
                "jdbc:h2:mem:sup_" + UUID.randomUUID() + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1", "sa", "");
        ds.setDriverClassName("org.h2.Driver");
        return new JdbcTemplate(ds);
    }

    @Test
    void groupsKiosksBySupervisorWithDisplayNameAndSortsByName() {
        JdbcTemplate jdbc = freshDb();
        jdbc.execute("CREATE TABLE users (id BIGINT PRIMARY KEY, username VARCHAR(50), first_name VARCHAR(100), last_name VARCHAR(100))");
        jdbc.execute("CREATE TABLE kiosk_supervisor_assignment (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                + "supervisor_user_id BIGINT NOT NULL, kiosk_location_id BIGINT NOT NULL, created_by_user_id BIGINT NOT NULL)");
        jdbc.update("INSERT INTO users VALUES (1, 'zoila', 'Zoila', 'Pérez')");
        jdbc.update("INSERT INTO users VALUES (2, 'gabriela.sup', NULL, NULL)");
        jdbc.update("INSERT INTO kiosk_supervisor_assignment (supervisor_user_id, kiosk_location_id, created_by_user_id) VALUES (1, 15, 9)");
        jdbc.update("INSERT INTO kiosk_supervisor_assignment (supervisor_user_id, kiosk_location_id, created_by_user_id) VALUES (1, 16, 9)");
        jdbc.update("INSERT INTO kiosk_supervisor_assignment (supervisor_user_id, kiosk_location_id, created_by_user_id) VALUES (2, 20, 9)");

        List<KioskSupervisorAssignmentReader.Supervisor> result = new KioskSupervisorAssignmentReader(jdbc).supervisors();

        assertThat(result).extracting(KioskSupervisorAssignmentReader.Supervisor::name)
                .containsExactly("gabriela.sup", "Zoila Pérez"); // sin nombre -> usuario; orden alfabético
        assertThat(result.get(1).kioskLocationIds()).containsExactly(15L, 16L);
        assertThat(result.get(0).kioskLocationIds()).containsExactly(20L);
    }

    @Test
    void returnsEmptyWhenTheModuleTableDoesNotExist() {
        assertThat(new KioskSupervisorAssignmentReader(freshDb()).supervisors()).isEmpty();
    }
}
