package com.fossiles.fossilescorebackend.application.service;

import com.fossiles.fossilescorebackend.application.util.KioskEffectiveGoals;
import com.fossiles.fossilescorebackend.infrastructure.persistence.entity.KioskSiteEntity;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;

/** Lee la tabla real del modulo Metas de kioscos (H2 en modo PostgreSQL) sin depender de sus clases. */
class KioskGoalModuleReaderTest {

    private static JdbcTemplate freshDb() {
        DriverManagerDataSource ds = new DriverManagerDataSource(
                "jdbc:h2:mem:goals_" + UUID.randomUUID() + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1", "sa", "");
        ds.setDriverClassName("org.h2.Driver");
        return new JdbcTemplate(ds);
    }

    private static void createGoalsTable(JdbcTemplate jdbc) {
        jdbc.execute("CREATE TABLE kiosk_monthly_goal (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                + "kiosk_location_id BIGINT NOT NULL, goal_year INT NOT NULL, goal_month INT NOT NULL, "
                + "goal_amount NUMERIC(12,2) NOT NULL, created_by_user_id BIGINT NOT NULL)");
    }

    @Test
    void readsGoalsOfTheYearByLocationAndMonth() {
        JdbcTemplate jdbc = freshDb();
        createGoalsTable(jdbc);
        jdbc.update("INSERT INTO kiosk_monthly_goal (kiosk_location_id, goal_year, goal_month, goal_amount, created_by_user_id) VALUES (15, 2026, 9, 130000.00, 1)");
        jdbc.update("INSERT INTO kiosk_monthly_goal (kiosk_location_id, goal_year, goal_month, goal_amount, created_by_user_id) VALUES (15, 2026, 10, 140000.00, 1)");
        jdbc.update("INSERT INTO kiosk_monthly_goal (kiosk_location_id, goal_year, goal_month, goal_amount, created_by_user_id) VALUES (16, 2026, 9, 90000.00, 1)");
        jdbc.update("INSERT INTO kiosk_monthly_goal (kiosk_location_id, goal_year, goal_month, goal_amount, created_by_user_id) VALUES (15, 2025, 9, 1.00, 1)");
        KioskGoalModuleReader reader = new KioskGoalModuleReader(jdbc);

        Map<Long, Map<Integer, BigDecimal>> goals = reader.goalsByLocation(2026);

        assertThat(goals).containsOnlyKeys(15L, 16L);
        assertThat(goals.get(15L)).containsOnlyKeys(9, 10);
        assertThat(goals.get(15L).get(9)).isEqualByComparingTo("130000");
        assertThat(goals.get(16L).get(9)).isEqualByComparingTo("90000");
    }

    @Test
    void forYearMapsSitesToLocationsAndIgnoresHistoricalSites() {
        JdbcTemplate jdbc = freshDb();
        createGoalsTable(jdbc);
        jdbc.update("INSERT INTO kiosk_monthly_goal (kiosk_location_id, goal_year, goal_month, goal_amount, created_by_user_id) VALUES (15, 2026, 9, 130000.00, 1)");
        KioskSiteEntity linked = KioskSiteEntity.builder().id(27L).name("MIRAFLORES II").locationId(15L).build();
        KioskSiteEntity historical = KioskSiteEntity.builder().id(15L).name("MAJADAS 11").locationId(null).build();

        KioskEffectiveGoals goals = new KioskGoalModuleReader(jdbc).forYear(2026, List.of(linked, historical));

        // El id del sitio (27) NO es el id de la location (15): se resuelve por location_id
        assertThat(goals.moduleGoal(27L, 9)).isEqualByComparingTo("130000");
        assertThat(goals.isManagedByGoalsModule(27L)).isTrue();
        assertThat(goals.moduleGoal(15L, 9)).isNull(); // sitio historico con id 15 no hereda la meta de la location 15
        assertThat(goals.isManagedByGoalsModule(15L)).isFalse();
    }

    @Test
    void returnsEmptyInsteadOfFailingWhenGoalsModuleTableDoesNotExist() {
        JdbcTemplate jdbc = freshDb(); // sin tabla kiosk_monthly_goal

        Map<Long, Map<Integer, BigDecimal>> goals = new KioskGoalModuleReader(jdbc).goalsByLocation(2026);

        assertThat(goals).isEmpty();
    }
}
