package com.fossiles.fossilescorebackend.application.service;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fossiles.fossilescorebackend.application.dto.request.KioskExcelCommitRequest;
import com.fossiles.fossilescorebackend.application.dto.response.KioskExcelBatchSummaryResponse;
import com.fossiles.fossilescorebackend.application.dto.response.KioskExcelCommitResponse;
import com.fossiles.fossilescorebackend.application.dto.response.KioskExcelDataDto;
import com.fossiles.fossilescorebackend.application.dto.response.KioskExcelIssueDto;
import com.fossiles.fossilescorebackend.application.dto.response.KioskExcelPreviewResponse;
import com.fossiles.fossilescorebackend.application.exception.BusinessException;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.transaction.support.TransactionTemplate;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Prueba el SQL del importador (commit/revert/preview) contra H2 en modo PostgreSQL con un esquema equivalente
 * al de scripts/migration-kiosk-financials.sql (sin índices parciales/de expresión).
 */
class KioskExcelImportServiceH2Test {

    private static final String SHA_A = "a".repeat(64);
    private static final String SHA_B = "b".repeat(64);

    private DriverManagerDataSource dataSource;
    private JdbcTemplate jdbc;
    private KioskExcelImportService service;
    private final ObjectMapper mapper = new ObjectMapper().findAndRegisterModules();

    @BeforeEach
    void setUp() {
        dataSource = new DriverManagerDataSource("jdbc:h2:mem:kiosk" + UUID.randomUUID()
                + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1;NON_KEYWORDS=YEAR,MONTH", "sa", "");
        jdbc = new JdbcTemplate(dataSource);
        createSchema();
        KioskFinancialsAccessGuard guard = Mockito.mock(KioskFinancialsAccessGuard.class);
        Mockito.when(guard.currentUserId()).thenReturn(42L);
        service = new KioskExcelImportService(new KioskExcelParser(), new NamedParameterJdbcTemplate(dataSource), guard, mapper);
    }

    private void createSchema() {
        jdbc.execute("CREATE TABLE kiosk_site (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(120) NOT NULL, "
                + "location_id BIGINT, status VARCHAR(20) DEFAULT 'ACTIVE' NOT NULL, closed_on DATE, pos_go_live_override DATE, "
                + "sort_order INT DEFAULT 0 NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "
                + "updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT uq_site_name UNIQUE (name))");
        jdbc.execute("CREATE TABLE kiosk_site_alias (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, alias_normalized VARCHAR(120) NOT NULL UNIQUE, "
                + "site_id BIGINT NOT NULL)");
        jdbc.execute("CREATE TABLE kiosk_cost_category (code VARCHAR(40) PRIMARY KEY, name VARCHAR(120) NOT NULL, "
                + "sort_order INT NOT NULL, active BOOLEAN DEFAULT TRUE NOT NULL)");
        jdbc.execute("CREATE TABLE kiosk_import_batch (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, file_name VARCHAR(255) NOT NULL, "
                + "file_sha256 VARCHAR(64) NOT NULL, year INT NOT NULL, month INT NOT NULL, status VARCHAR(20) DEFAULT 'APPLIED' NOT NULL, "
                + "sales_rows INT DEFAULT 0 NOT NULL, config_rows INT DEFAULT 0 NOT NULL, cost_rows INT DEFAULT 0 NOT NULL, "
                + "warnings_json CLOB, created_by BIGINT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "
                + "reverted_by BIGINT, reverted_at TIMESTAMP)");
        jdbc.execute("CREATE TABLE kiosk_fixed_cost (site_id BIGINT NOT NULL, year INT NOT NULL, month INT NOT NULL, "
                + "category_code VARCHAR(40) NOT NULL, amount NUMERIC(12,2) NOT NULL, updated_by BIGINT, "
                + "updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, import_batch_id BIGINT, "
                + "PRIMARY KEY (site_id, year, month, category_code))");
        jdbc.execute("CREATE TABLE kiosk_period_config (site_id BIGINT NOT NULL, year INT NOT NULL, month INT NOT NULL, "
                + "sales_goal NUMERIC(12,2), product_cost_pct NUMERIC(6,4), sales_commission_pct NUMERIC(6,4), "
                + "card_commission_pct NUMERIC(6,4), tax_pct NUMERIC(6,4), source VARCHAR(20) DEFAULT 'MANUAL' NOT NULL, "
                + "updated_by BIGINT, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, import_batch_id BIGINT, "
                + "PRIMARY KEY (site_id, year, month))");
        jdbc.execute("CREATE TABLE kiosk_daily_sales_hist (site_id BIGINT NOT NULL, sale_date DATE NOT NULL, "
                + "amount NUMERIC(12,2) NOT NULL, import_batch_id BIGINT, PRIMARY KEY (site_id, sale_date))");
        jdbc.execute("CREATE TABLE kiosk_sale (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, kiosk_location_id BIGINT, sale_date DATE, "
                + "test_sale BOOLEAN DEFAULT FALSE NOT NULL, status VARCHAR(30))");

        String[] codes = {"ALQUILER", "LUZ", "TELEFONO_INTERNET_PROG", "MANTENIMIENTO", "SALARIOS_MO_INDIRECTA",
                "BONIFICACION", "INDEMNIZACION_VACACIONES", "BONO_14", "AGUINALDO", "SALARIOS_MO_DIRECTA"};
        for (int i = 0; i < codes.length; i++) {
            jdbc.update("INSERT INTO kiosk_cost_category (code, name, sort_order) VALUES (?, ?, ?)", codes[i], codes[i], i + 1);
        }
        // sitio 1 = MIRAFLORES (location 15), sitio 2 = PERI (sin location)
        jdbc.update("INSERT INTO kiosk_site (name, location_id, status) VALUES ('MIRAFLORES II', 15, 'ACTIVE')");
        jdbc.update("INSERT INTO kiosk_site (name, location_id, status) VALUES ('PERI', NULL, 'ACTIVE')");
        jdbc.update("INSERT INTO kiosk_site_alias (alias_normalized, site_id) VALUES ('MIRAFLORES', 1)");
        jdbc.update("INSERT INTO kiosk_site_alias (alias_normalized, site_id) VALUES ('PERI', 2)");
    }

    // ------------------------------------------------------------------ fixtures

    private static Map<String, BigDecimal> values(Object... kv) {
        Map<String, BigDecimal> m = new LinkedHashMap<>();
        for (int i = 0; i < kv.length; i += 2) {
            Object v = kv[i + 1];
            m.put((String) kv[i], v == null ? null : new BigDecimal(v.toString()));
        }
        return m;
    }

    private static KioskExcelDataDto augustData() {
        List<KioskExcelDataDto.Day> days = new ArrayList<>();
        days.add(day(1, values("MIRAFLORES", null, "PERI", null)));
        days.add(day(2, values("MIRAFLORES", "100.5", "PERI", "0")));
        days.add(day(3, values("MIRAFLORES", "200", "PERI", null)));
        Map<String, KioskExcelDataDto.Rates> rates = new LinkedHashMap<>();
        rates.put("MIRAFLORES", KioskExcelDataDto.Rates.builder().productCostPct(new BigDecimal("0.18"))
                .salesCommissionPct(new BigDecimal("0.04")).cardCommissionPct(new BigDecimal("0.025"))
                .taxPct(new BigDecimal("0.025")).build());
        Map<String, Map<String, BigDecimal>> costs = new LinkedHashMap<>();
        Map<String, BigDecimal> c = new LinkedHashMap<>();
        c.put("ALQUILER", new BigDecimal("14674.89"));
        c.put("LUZ", null);
        costs.put("MIRAFLORES", c);
        Map<String, BigDecimal> goals = new LinkedHashMap<>();
        goals.put("MIRAFLORES", new BigDecimal("130000"));
        goals.put("PERI", BigDecimal.ZERO);
        return KioskExcelDataDto.builder().days(days).goals(goals).rates(rates).costs(costs)
                .blockedCells(new ArrayList<>()).build();
    }

    private static KioskExcelDataDto.Day day(int d, Map<String, BigDecimal> values) {
        return KioskExcelDataDto.Day.builder().date(LocalDate.of(2025, 8, d)).values(values).build();
    }

    private static KioskExcelCommitRequest request(boolean replace, KioskExcelDataDto data, String sha) {
        KioskExcelCommitRequest.FileCommit f = KioskExcelCommitRequest.FileCommit.builder()
                .fileName("VENTAS AGOSTO 2025.xlsx").sha256(sha).year(2025).month(8)
                .siteMapping(new LinkedHashMap<>()).resolutions(new LinkedHashMap<>()).data(data).build();
        return KioskExcelCommitRequest.builder().replaceExisting(replace).files(List.of(f)).build();
    }

    private int count(String sql, Object... args) {
        Integer n = jdbc.queryForObject(sql, Integer.class, args);
        return n == null ? 0 : n;
    }

    // ------------------------------------------------------------------ commit

    @Test
    void commitWritesSalesConfigAndCostsTaggedWithTheBatch() throws Exception {
        KioskExcelCommitResponse res = service.commit(request(false, augustData(), SHA_A));

        assertThat(res.getBatches()).hasSize(1);
        KioskExcelCommitResponse.BatchResult b = res.getBatches().get(0);
        assertThat(b.getSalesRows()).isEqualTo(3);   // null = sin fila; 0 = fila
        assertThat(b.getConfigRows()).isEqualTo(1);  // PERI sólo trae meta 0 => sin config
        assertThat(b.getCostRows()).isEqualTo(1);    // LUZ null no se escribe
        assertThat(b.getReplacedRows()).isZero();
        assertThat(b.getWarnings()).anyMatch(w -> w.startsWith("MISSING_GOAL"));

        assertThat(count("SELECT COUNT(*) FROM kiosk_daily_sales_hist WHERE import_batch_id = ?", b.getBatchId())).isEqualTo(3);
        assertThat(jdbc.queryForObject("SELECT amount FROM kiosk_daily_sales_hist WHERE site_id = 1 AND sale_date = DATE '2025-08-02'",
                BigDecimal.class)).isEqualByComparingTo("100.50");
        assertThat(jdbc.queryForObject("SELECT amount FROM kiosk_daily_sales_hist WHERE site_id = 2 AND sale_date = DATE '2025-08-02'",
                BigDecimal.class)).isEqualByComparingTo("0");
        assertThat(count("SELECT COUNT(*) FROM kiosk_daily_sales_hist WHERE sale_date = DATE '2025-08-01'")).isZero();
        Map<String, Object> cfg = jdbc.queryForMap("SELECT * FROM kiosk_period_config WHERE site_id = 1 AND year = 2025 AND month = 8");
        assertThat(cfg.get("SOURCE")).isEqualTo("EXCEL");
        assertThat((BigDecimal) cfg.get("SALES_GOAL")).isEqualByComparingTo("130000");
        assertThat((BigDecimal) cfg.get("CARD_COMMISSION_PCT")).isEqualByComparingTo("0.025");
        assertThat(((Number) cfg.get("IMPORT_BATCH_ID")).longValue()).isEqualTo(b.getBatchId());
        assertThat(((Number) cfg.get("UPDATED_BY")).longValue()).isEqualTo(42L);
        assertThat(count("SELECT COUNT(*) FROM kiosk_fixed_cost WHERE import_batch_id = ? AND category_code = 'ALQUILER'", b.getBatchId())).isEqualTo(1);

        Map<String, Object> batch = jdbc.queryForMap("SELECT * FROM kiosk_import_batch WHERE id = ?", b.getBatchId());
        assertThat(batch.get("STATUS")).isEqualTo("APPLIED");
        assertThat(((Number) batch.get("SALES_ROWS")).intValue()).isEqualTo(3);
        assertThat(((Number) batch.get("CREATED_BY")).longValue()).isEqualTo(42L);
        assertThat(service.list()).hasSize(1);
        assertThat(service.list().get(0).getWarnings()).isNotEmpty();
    }

    @Test
    void commitCreatesHistoricalSiteAndAliasForNewColumns() throws Exception {
        KioskExcelDataDto data = augustData();
        data.getDays().get(1).getValues().put("SANTA AMELIA", new BigDecimal("77.25"));
        KioskExcelCommitRequest req = request(false, data, SHA_A);
        req.getFiles().get(0).getSiteMapping().put("SANTA AMELIA", KioskExcelCommitRequest.SiteMappingEntry.builder()
                .create(KioskExcelCommitRequest.CreateSite.builder().name("SANTA AMELIA").status("CLOSED")
                        .closedOn(LocalDate.of(2025, 8, 31)).build()).build());
        // mapeo manual de una columna con otro nombre al sitio existente 2 => alias nuevo
        data.getDays().get(1).getValues().put("PERI NORTE", new BigDecimal("3"));
        req.getFiles().get(0).getSiteMapping().put("PERI NORTE", KioskExcelCommitRequest.SiteMappingEntry.builder().siteId(2L).build());
        // ...pero PERI ya apunta al sitio 2: debe rechazarse por duplicado
        assertThatThrownBy(() -> service.commit(req)).isInstanceOf(BusinessException.class).hasMessageContaining("mismo sitio");

        data.getDays().get(1).getValues().remove("PERI NORTE");
        req.getFiles().get(0).getSiteMapping().remove("PERI NORTE");
        service.commit(req);

        Map<String, Object> site = jdbc.queryForMap("SELECT * FROM kiosk_site WHERE name = 'SANTA AMELIA'");
        assertThat(site.get("LOCATION_ID")).isNull();
        assertThat(site.get("STATUS")).isEqualTo("CLOSED");
        assertThat(site.get("CLOSED_ON").toString()).isEqualTo("2025-08-31");
        long id = ((Number) site.get("ID")).longValue();
        assertThat(count("SELECT COUNT(*) FROM kiosk_site_alias WHERE alias_normalized = 'SANTA AMELIA' AND site_id = ?", id)).isEqualTo(1);
        assertThat(count("SELECT COUNT(*) FROM kiosk_daily_sales_hist WHERE site_id = ?", id)).isEqualTo(1);
    }

    @Test
    void manualMappingCreatesNewAlias() throws Exception {
        KioskExcelDataDto data = augustData();
        data.getDays().get(1).getValues().put("SANTAL�", new BigDecimal("9"));
        KioskExcelCommitRequest req = request(false, data, SHA_A);
        jdbc.update("INSERT INTO kiosk_site (name, location_id, status) VALUES ('SANTALU', 33, 'ACTIVE')");
        req.getFiles().get(0).getSiteMapping().put("SANTAL�",
                KioskExcelCommitRequest.SiteMappingEntry.builder().siteId(3L).build());
        service.commit(req);
        assertThat(count("SELECT COUNT(*) FROM kiosk_site_alias WHERE alias_normalized = 'SANTAL' AND site_id = 3")).isEqualTo(1);
    }

    @Test
    void existingDataRequiresReplaceAndIsThenReplaced() throws Exception {
        service.commit(request(false, augustData(), SHA_A));

        assertThatThrownBy(() -> service.commit(request(false, augustData(), SHA_B)))
                .isInstanceOf(BusinessException.class).hasMessageContaining("replaceExisting");

        KioskExcelDataDto changed = augustData();
        changed.getDays().get(1).getValues().put("MIRAFLORES", new BigDecimal("999.99"));
        changed.getDays().get(2).getValues().put("MIRAFLORES", null);
        changed.getCosts().get("MIRAFLORES").put("ALQUILER", new BigDecimal("1"));
        KioskExcelCommitResponse res = service.commit(request(true, changed, SHA_B));

        assertThat(res.getBatches().get(0).getReplacedRows()).isEqualTo(3 + 1 + 1);
        assertThat(count("SELECT COUNT(*) FROM kiosk_daily_sales_hist WHERE site_id = 1")).isEqualTo(1);
        assertThat(jdbc.queryForObject("SELECT amount FROM kiosk_daily_sales_hist WHERE site_id = 1", BigDecimal.class))
                .isEqualByComparingTo("999.99");
        assertThat(jdbc.queryForObject("SELECT amount FROM kiosk_fixed_cost WHERE site_id = 1 AND category_code = 'ALQUILER'",
                BigDecimal.class)).isEqualByComparingTo("1");
        assertThat(count("SELECT COUNT(*) FROM kiosk_import_batch")).isEqualTo(2);
    }

    @Test
    void rejectedCommitWritesNothing() {
        KioskExcelDataDto data = augustData();
        data.getDays().get(1).getValues().put("MIRAFLORES", new BigDecimal("-1"));
        assertThatThrownBy(() -> service.commit(request(true, data, SHA_A)))
                .isInstanceOf(BusinessException.class).hasMessageContaining("negativa");
        assertThat(count("SELECT COUNT(*) FROM kiosk_import_batch")).isZero();
        assertThat(count("SELECT COUNT(*) FROM kiosk_daily_sales_hist")).isZero();
    }

    @Test
    void failureInSecondFileRollsBackEverythingInsideOneTransaction() {
        // Archivo 1 (ago) válido; archivo 2 (sep) choca con datos existentes de sep y replaceExisting=false.
        jdbc.update("INSERT INTO kiosk_daily_sales_hist (site_id, sale_date, amount) VALUES (1, DATE '2025-09-05', 10)");
        KioskExcelCommitRequest req = request(false, augustData(), SHA_A);
        KioskExcelDataDto sep = KioskExcelDataDto.builder().days(List.of(KioskExcelDataDto.Day.builder()
                        .date(LocalDate.of(2025, 9, 2)).values(values("MIRAFLORES", "50")).build()))
                .goals(new LinkedHashMap<>()).rates(new LinkedHashMap<>()).costs(new LinkedHashMap<>())
                .blockedCells(new ArrayList<>()).build();
        List<KioskExcelCommitRequest.FileCommit> files = new ArrayList<>(req.getFiles());
        files.add(KioskExcelCommitRequest.FileCommit.builder().fileName("VENTAS SEPTIEMBRE 2025.xlsx").sha256(SHA_B)
                .year(2025).month(9).siteMapping(new LinkedHashMap<>()).resolutions(new LinkedHashMap<>()).data(sep).build());
        req.setFiles(files);

        TransactionTemplate tx = new TransactionTemplate(new DataSourceTransactionManager(dataSource));
        assertThatThrownBy(() -> tx.executeWithoutResult(status -> {
            try {
                service.commit(req);
            } catch (BusinessException e) {
                throw new IllegalStateException(e.getMessage(), e);
            }
        })).hasMessageContaining("replaceExisting");

        assertThat(count("SELECT COUNT(*) FROM kiosk_import_batch")).isZero();
        assertThat(count("SELECT COUNT(*) FROM kiosk_daily_sales_hist")).isEqualTo(1);
        assertThat(count("SELECT COUNT(*) FROM kiosk_period_config")).isZero();
    }

    @Test
    void histRowsOnOrAfterPosGoLiveWarnButAreStillWritten() throws Exception {
        // sitio 1 (location 15): 1a venta real 2025-08-03; ventas de prueba y VOID anteriores no cuentan
        jdbc.update("INSERT INTO kiosk_sale (kiosk_location_id, sale_date, test_sale, status) VALUES (15, DATE '2025-08-03', FALSE, 'COMPLETED')");
        jdbc.update("INSERT INTO kiosk_sale (kiosk_location_id, sale_date, test_sale, status) VALUES (15, DATE '2025-08-01', TRUE, 'COMPLETED')");
        jdbc.update("INSERT INTO kiosk_sale (kiosk_location_id, sale_date, test_sale, status) VALUES (15, DATE '2025-07-01', FALSE, 'VOID')");
        jdbc.update("INSERT INTO kiosk_sale (kiosk_location_id, sale_date, test_sale, status) VALUES (15, DATE '2025-07-02', FALSE, 'CANCELLED')");
        // sitio 2: override manda
        jdbc.update("UPDATE kiosk_site SET pos_go_live_override = DATE '2025-08-02' WHERE id = 2");

        KioskExcelCommitResponse res = service.commit(request(false, augustData(), SHA_A));
        List<String> warnings = res.getBatches().get(0).getWarnings();
        assertThat(warnings.stream().filter(w -> w.startsWith("OVERLAPS_POS"))).hasSize(2);
        assertThat(warnings).anyMatch(w -> w.contains("'MIRAFLORES'") && w.contains("tiene 1 d") && w.contains("2025-08-03"));
        assertThat(warnings).anyMatch(w -> w.contains("'PERI'") && w.contains("2025-08-02"));
        assertThat(res.getBatches().get(0).getSalesRows()).isEqualTo(3);
    }

    // ------------------------------------------------------------------ revert

    @Test
    void revertDeletesOnlyRowsOfThatBatchAndCannotBeRepeated() throws Exception {
        Long first = service.commit(request(false, augustData(), SHA_A)).getBatches().get(0).getBatchId();
        // datos de otro mes/lote que no deben tocarse
        KioskExcelDataDto sep = KioskExcelDataDto.builder().days(List.of(KioskExcelDataDto.Day.builder()
                        .date(LocalDate.of(2025, 9, 2)).values(values("MIRAFLORES", "50")).build()))
                .goals(new LinkedHashMap<>()).rates(new LinkedHashMap<>()).costs(new LinkedHashMap<>())
                .blockedCells(new ArrayList<>()).build();
        KioskExcelCommitRequest sepReq = request(false, sep, SHA_B);
        sepReq.getFiles().get(0).setMonth(9);
        Long second = service.commit(sepReq).getBatches().get(0).getBatchId();
        // edición manual posterior de la config de agosto: debe respetarse al revertir
        jdbc.update("UPDATE kiosk_period_config SET source = 'MANUAL' WHERE site_id = 1 AND month = 8");

        KioskExcelBatchSummaryResponse reverted = service.revert(first);
        assertThat(reverted.getStatus()).isEqualTo("REVERTED");
        assertThat(reverted.getRevertedBy()).isEqualTo(42L);
        assertThat(reverted.getRevertedAt()).isNotNull();
        assertThat(count("SELECT COUNT(*) FROM kiosk_daily_sales_hist WHERE import_batch_id = ?", first)).isZero();
        assertThat(count("SELECT COUNT(*) FROM kiosk_fixed_cost WHERE import_batch_id = ?", first)).isZero();
        assertThat(count("SELECT COUNT(*) FROM kiosk_period_config WHERE site_id = 1 AND month = 8")).isEqualTo(1);
        assertThat(count("SELECT COUNT(*) FROM kiosk_daily_sales_hist WHERE import_batch_id = ?", second)).isEqualTo(1);

        assertThatThrownBy(() -> service.revert(first)).isInstanceOf(BusinessException.class)
                .hasMessageContaining("ya fue revertido");
        assertThatThrownBy(() -> service.revert(9999L)).hasMessageContaining("no encontrado");
    }

    // ------------------------------------------------------------------ preview -> commit (roundtrip JSON)

    @Test
    void previewMatchesAliasesFlagsUnmatchedAndRoundTripsIntoCommit() throws Exception {
        byte[] xlsx = KioskExcelTestFixtures.februaryWorkbook("150..5", false, null);

        KioskExcelPreviewResponse preview = service.previewBytes(List.of(
                new KioskExcelImportService.NamedBytes("VENTAS FEBRERO 2025.xlsx", xlsx)));
        KioskExcelPreviewResponse.FilePreview file = preview.getFiles().get(0);
        assertThat(file.getYear()).isEqualTo(2025);
        assertThat(file.getMonth()).isEqualTo(2);
        assertThat(file.getSha256()).hasSize(64);
        assertThat(file.getAlreadyImported()).isNull();
        assertThat(file.getColumns()).extracting(KioskExcelPreviewResponse.ColumnMapping::getMatchStatus)
                .containsExactly("MATCHED", "MATCHED", "UNMATCHED");
        assertThat(file.getColumns().get(0).getMatchedSiteId()).isEqualTo(1L);
        assertThat(file.getColumns().get(0).getNormalized()).isEqualTo("MIRAFLORES");
        List<KioskExcelIssueDto> blocking = file.getIssues().stream().filter(i -> "BLOCKING".equals(i.getSeverity())).toList();
        assertThat(blocking).extracting(KioskExcelIssueDto::getCode)
                .containsExactlyInAnyOrder("NON_NUMERIC_CELL", "UNMATCHED_COLUMN");
        assertThat(file.getIssues()).extracting(KioskExcelIssueDto::getId).doesNotHaveDuplicates();
        assertThat(file.getStats().getColumns()).isEqualTo(3);
        assertThat(file.getStats().getDays()).isEqualTo(28);

        // preview -> JSON -> commit (como lo hace el front)
        String json = mapper.writeValueAsString(file.getData());
        KioskExcelDataDto data = mapper.readValue(json, KioskExcelDataDto.class);
        String issueId = blocking.stream().filter(i -> "NON_NUMERIC_CELL".equals(i.getCode())).findFirst().orElseThrow().getId();
        String commitJson = "{\"replaceExisting\":false,\"files\":[{\"fileName\":\"VENTAS FEBRERO 2025.xlsx\",\"sha256\":\""
                + file.getSha256() + "\",\"year\":2025,\"month\":2,"
                + "\"siteMapping\":{\"NUEVO KIOSCO\":{\"create\":{\"name\":\"NUEVO KIOSCO\"}}},"
                + "\"resolutions\":{\"" + issueId + "\":150.5},\"data\":" + mapper.writeValueAsString(data) + "}]}";
        KioskExcelCommitRequest request = mapper.readValue(commitJson, KioskExcelCommitRequest.class);

        KioskExcelCommitResponse res = service.commit(request);
        KioskExcelCommitResponse.BatchResult b = res.getBatches().get(0);
        assertThat(b.getSalesRows()).isEqualTo(27 * 3);
        assertThat(b.getConfigRows()).isEqualTo(3 - 0);   // NUEVO KIOSCO: meta 0 pero con tasas
        assertThat(b.getCostRows()).isEqualTo(10 + 10 + 8);
        assertThat(jdbc.queryForObject("SELECT amount FROM kiosk_daily_sales_hist WHERE site_id = 2 AND sale_date = DATE '2025-02-10'",
                BigDecimal.class)).isEqualByComparingTo("150.5");
        assertThat(count("SELECT COUNT(*) FROM kiosk_site WHERE name = 'NUEVO KIOSCO' AND location_id IS NULL")).isEqualTo(1);
        assertThat(jdbc.queryForObject("SELECT sales_goal FROM kiosk_period_config WHERE site_id = 3", BigDecimal.class)).isNull();

        // segunda vista previa: ya importado (mismo archivo) + DUPLICATE_FILE; sitio nuevo ya tiene alias
        KioskExcelPreviewResponse.FilePreview again = service.previewBytes(List.of(
                new KioskExcelImportService.NamedBytes("VENTAS FEBRERO 2025.xlsx", xlsx))).getFiles().get(0);
        assertThat(again.getAlreadyImported()).isNotNull();
        assertThat(again.getAlreadyImported().getBatchId()).isEqualTo(b.getBatchId());
        assertThat(again.getAlreadyImported().isSameFile()).isTrue();
        assertThat(again.getIssues()).extracting(KioskExcelIssueDto::getCode).contains("DUPLICATE_FILE");
        assertThat(again.getColumns()).extracting(KioskExcelPreviewResponse.ColumnMapping::getMatchStatus)
                .containsOnly("MATCHED");

        // tras revertir ya no figura como importado
        service.revert(b.getBatchId());
        KioskExcelPreviewResponse.FilePreview third = service.previewBytes(List.of(
                new KioskExcelImportService.NamedBytes("VENTAS FEBRERO 2025.xlsx", xlsx))).getFiles().get(0);
        assertThat(third.getAlreadyImported()).isNull();
    }

    @Test
    void previewMarksTwoColumnsOfTheSameSiteAsAmbiguousAndBrokenFilesAsFileError() throws Exception {
        jdbc.update("INSERT INTO kiosk_site_alias (alias_normalized, site_id) VALUES ('NUEVO KIOSCO', 1)");
        byte[] xlsx = KioskExcelTestFixtures.februaryWorkbook(null, false, null);
        KioskExcelPreviewResponse preview = service.previewBytes(List.of(
                new KioskExcelImportService.NamedBytes("VENTAS FEBRERO 2025.xlsx", xlsx),
                new KioskExcelImportService.NamedBytes("VENTAS FEBRERO 2025 copia.xlsx", xlsx),
                new KioskExcelImportService.NamedBytes("~$VENTAS.xlsx", new byte[]{1, 2, 3})));
        KioskExcelPreviewResponse.FilePreview first = preview.getFiles().get(0);
        assertThat(first.getColumns()).extracting(KioskExcelPreviewResponse.ColumnMapping::getMatchStatus)
                .containsExactly("AMBIGUOUS", "MATCHED", "AMBIGUOUS");
        // mismo archivo repetido en la carga
        assertThat(preview.getFiles().get(1).getIssues()).extracting(KioskExcelIssueDto::getCode).contains("DUPLICATE_FILE");
        KioskExcelPreviewResponse.FilePreview broken = preview.getFiles().get(2);
        assertThat(broken.getData()).isNull();
        assertThat(broken.getIssues()).extracting(KioskExcelIssueDto::getCode).containsExactly("FILE_ERROR");
        assertThat(broken.getIssues().get(0).getSeverity()).isEqualTo("BLOCKING");
    }

    @Test
    void previewWarnsAboutPosOverlapForMatchedSites() {
        jdbc.update("INSERT INTO kiosk_sale (kiosk_location_id, sale_date, test_sale, status) VALUES (15, DATE '2025-02-20', FALSE, 'COMPLETED')");
        byte[] xlsx;
        try {
            xlsx = KioskExcelTestFixtures.februaryWorkbook(null, false, null);
        } catch (Exception e) {
            throw new IllegalStateException(e);
        }
        KioskExcelPreviewResponse.FilePreview file = service.previewBytes(List.of(
                new KioskExcelImportService.NamedBytes("VENTAS FEBRERO 2025.xlsx", xlsx))).getFiles().get(0);
        List<KioskExcelIssueDto> overlaps = file.getIssues().stream().filter(i -> "OVERLAPS_POS".equals(i.getCode())).toList();
        assertThat(overlaps).hasSize(1);
        assertThat(overlaps.get(0).getSeverity()).isEqualTo("WARNING");
        assertThat(overlaps.get(0).getMessage()).contains("MIRAFLORES").contains("tiene 9 d");
    }

    @Test
    void sha256IsStableHex() {
        assertThat(KioskExcelImportService.sha256("abc".getBytes()))
                .isEqualTo("ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad");
    }
}
