package com.fossiles.fossilescorebackend.infrastructure.controller;

import com.fossiles.fossilescorebackend.application.dto.request.MaterialRequestRequest;
import com.fossiles.fossilescorebackend.application.dto.request.MaterialRequestReviewRequest;
import com.fossiles.fossilescorebackend.application.dto.response.MaterialRequestResponse;
import com.fossiles.fossilescorebackend.application.exception.BusinessException;
import com.fossiles.fossilescorebackend.application.exception.ResourceNotFoundException;
import com.fossiles.fossilescorebackend.application.service.PurchaseService;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.net.URI;
import java.util.List;

@RestController
@RequestMapping("/api/material-requests")
@RequiredArgsConstructor
public class MaterialRequestController {

    private final PurchaseService purchaseService;

    @GetMapping
    public ResponseEntity<List<MaterialRequestResponse>> getAll(
            @RequestParam(required = false) String status,
            @RequestParam(required = false) String origin,
            @RequestParam(required = false) Boolean autoGenerated) {
        List<MaterialRequestResponse> requests = purchaseService.getMaterialRequestsByStatus(status);
        
        // Filtrar por origen si se especifica
        if (origin != null && !origin.isEmpty()) {
            requests = requests.stream()
                    .filter(r -> origin.equals(r.getOrigin()))
                    .collect(java.util.stream.Collectors.toList());
        }
        
        // Filtrar solicitudes generadas automáticamente (tienen observaciones específicas)
        if (autoGenerated != null && autoGenerated) {
            requests = requests.stream()
                    .filter(r -> r.getObservations() != null && 
                            r.getObservations().contains("Generada automáticamente"))
                    .collect(java.util.stream.Collectors.toList());
        }
        
        return ResponseEntity.ok(requests);
    }

    @GetMapping("/{id}")
    public ResponseEntity<MaterialRequestResponse> getById(@PathVariable Long id) throws ResourceNotFoundException {
        MaterialRequestResponse request = purchaseService.getMaterialRequestById(id);
        return ResponseEntity.ok(request);
    }

    @PostMapping
    public ResponseEntity<MaterialRequestResponse> create(
            @Valid @RequestBody MaterialRequestRequest request) throws ResourceNotFoundException, BusinessException {
        MaterialRequestResponse response = purchaseService.createMaterialRequest(request);
        return ResponseEntity.created(URI.create("/api/material-requests/" + response.getId()))
                .body(response);
    }

    @PutMapping("/{id}")
    public ResponseEntity<MaterialRequestResponse> update(
            @PathVariable Long id,
            @Valid @RequestBody MaterialRequestRequest request) throws ResourceNotFoundException, BusinessException {
        MaterialRequestResponse response = purchaseService.updateMaterialRequest(id, request);
        return ResponseEntity.ok(response);
    }

    @PutMapping("/{id}/approve")
    public ResponseEntity<MaterialRequestResponse> approve(
            @PathVariable Long id,
            @RequestParam(required = false) Long approvedBy) throws BusinessException, ResourceNotFoundException {
        MaterialRequestResponse response = purchaseService.approveMaterialRequest(id, approvedBy);
        return ResponseEntity.ok(response);
    }

    @PutMapping("/{id}/reject")
    public ResponseEntity<MaterialRequestResponse> reject(
            @PathVariable Long id,
            @RequestParam(required = false) Long rejectedBy,
            @RequestParam(required = false) String rejectionReason) throws BusinessException, ResourceNotFoundException {
        MaterialRequestResponse response = purchaseService.rejectMaterialRequest(id, rejectedBy, rejectionReason);
        return ResponseEntity.ok(response);
    }

    @PutMapping("/{id}/review-comments")
    public ResponseEntity<MaterialRequestResponse> addReviewComments(
            @PathVariable Long id,
            @RequestBody MaterialRequestReviewRequest request) throws ResourceNotFoundException {
        MaterialRequestResponse response = purchaseService.addReviewComments(id, request.getReviewComments());
        return ResponseEntity.ok(response);
    }

    @DeleteMapping("/{id}")
    public ResponseEntity<Void> delete(@PathVariable Long id) throws BusinessException, ResourceNotFoundException {
        purchaseService.deleteMaterialRequest(id);
        return ResponseEntity.noContent().build();
    }
}

